# CRYPTO TRADING SIGNAL SYSTEM
# Main Docker Compose Configuration
# ============================================

# ==================== NETWORKS ====================
networks:
  crypto-network:
    driver: bridge

# ==================== VOLUMES ====================
volumes:
  mysql_data:
    driver: local
  timescaledb_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# ==================== SERVICES ====================
services:

  # ==================== DATABASES ====================
  # MySQL - Primary Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "7100:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schemas/complete_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./infrastructure/databases/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - crypto-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    
  # TimescaleDB - Time-Series Database
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: crypto-timescaledb
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      POSTGRES_DB: ${TIMESCALE_DB} # Creates database: crypto_timeseries
      POSTGRES_USER: ${TIMESCALE_USER} # Creates user: timescale_user
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust # Allow local connections
    ports:
      - "7101:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/schemas/timescale_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - crypto-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DB} -h localhost" ] # Fixed: specify database
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give more time for init
    platform: linux/amd64

  # Redis - Cache & Real-time Data
  redis:
    image: redis:7-alpine
    container_name: crypto-redis
    restart: unless-stopped
    ports:
      - "7102:6379"
    volumes:
      - redis_data:/data
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - crypto-network
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB - ML Models Storage
  mongodb:
    image: mongo:6
    container_name: crypto-mongodb
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "7103:27017" # Fixed port from 71303
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: crypto-rabbitmq
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - crypto-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================== BACKEND ====================
  # NestJS API Gateway
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: crypto-api-gateway
    restart: unless-stopped
    env_file:
      - secrets/database.txt
      - secrets/api-keys.txt
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000

      # Database connections
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

      TIMESCALE_HOST: timescaledb
      TIMESCALE_PORT: 5432

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

      # JWT Secret
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-7d}

      # CORS
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3001}
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/api-gateway/logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== PYTHON BOTS ====================
  # Market Data Collector Bot
  # ==================== PYTHON BOTS ====================
  # Market Data Collector Bot - FIXED VERSION
  market-data-bot:
    build:
      context: .  # Build from root directory
      dockerfile: backend/bots/market-data-bot/Dockerfile
    container_name: crypto-market-data-bot
    restart: unless-stopped
    env_file:
      - secrets/api-keys.txt
    environment:
      # Database connections
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-crypto_trading}
      MYSQL_USER: ${MYSQL_USER:-crypto_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
      # TimescaleDB
      TIMESCALEDB_HOST: timescaledb
      TIMESCALEDB_PORT: 5432
      TIMESCALEDB_DATABASE: ${TIMESCALE_DB:-crypto_timeseries}
      TIMESCALEDB_USER: ${TIMESCALE_USER:-timescale_user}
      TIMESCALEDB_PASSWORD: ${TIMESCALE_PASSWORD}
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      
      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      
      # Exchange API Keys
      BINANCE_API_KEY: ${BINANCE_API_KEY:-}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET:-}
      
      # Bot Config
      CONFIG_PATH: /app/config.yaml
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/market-data-bot/logs:/var/log/market-data-bot
      - ./backend/bots/market-data-bot/config.yaml:/app/config.yaml
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; r=redis.Redis(host='redis', port=6379); r.ping()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
  # News Collector Bot
  news-collector-bot:
    build:
      context: ./backend/bots/news-collector-bot
      dockerfile: Dockerfile
    container_name: crypto-news-collector-bot
    restart: unless-stopped
    env_file:
      - secrets/database.txt
      - secrets/api-keys.txt
    environment:
      # Bot Config
      COLLECTION_INTERVAL: ${NEWS_COLLECTION_INTERVAL:-300}
      SYMBOLS: ${CRYPTO_SYMBOLS:-BTC,ETH,SOL}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/news-collector-bot/logs:/app/logs

  # Technical Analysis Bot
  technical-analysis-bot:
    build:
      context: ./backend/bots/technical-analysis-bot
      dockerfile: Dockerfile
    container_name: crypto-technical-bot
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      ANALYSIS_INTERVAL: ${TECH_ANALYSIS_INTERVAL:-60}
      TIMEFRAMES: ${TIMEFRAMES:-1h,4h,1d}
    depends_on:
      mysql:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/technical-analysis-bot/logs:/app/logs

  # Sentiment Analysis Bot
  sentiment-analysis-bot:
    build:
      context: ./backend/bots/sentiment-analysis-bot
      dockerfile: Dockerfile
    container_name: crypto-sentiment-bot
    restart: unless-stopped
    env_file:
      - secrets/database.txt
      - secrets/api-keys.txt
    environment:
      ANALYSIS_INTERVAL: ${SENTIMENT_ANALYSIS_INTERVAL:-300}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/sentiment-analysis-bot/logs:/app/logs
      - ./backend/bots/sentiment-analysis-bot/models:/app/models

  # ICT Analysis Bot
  itc-analysis-bot:
    build:
      context: ./backend/bots/itc-analysis-bot
      dockerfile: Dockerfile
    container_name: crypto-itc-bot
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      ANALYSIS_INTERVAL: ${ITC_ANALYSIS_INTERVAL:-300}
    depends_on:
      mysql:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/itc-analysis-bot/logs:/app/logs

  # Signal Aggregator Bot
  signal-aggregator-bot:
    build:
      context: ./backend/bots/signal-aggregator-bot
      dockerfile: Dockerfile
    container_name: crypto-signal-aggregator
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      # Signal validation thresholds
      MIN_RR_RATIO: ${MIN_RR_RATIO:-4.0}
      MIN_CONFIDENCE: ${MIN_CONFIDENCE:-60}
      MIN_WIN_RATE: ${MIN_WIN_RATE:-60}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/signal-aggregator-bot/logs:/app/logs

  # ML Learning Engine
  ml-learning-engine:
    build:
      context: ./backend/bots/ml-learning-engine
      dockerfile: Dockerfile
    container_name: crypto-ml-engine
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    environment:
      # Training config
      TRAINING_INTERVAL: ${ML_TRAINING_INTERVAL:-86400}
      AUTO_RETRAIN: ${ML_AUTO_RETRAIN:-true}
    depends_on:
      mysql:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/ml-learning-engine/logs:/app/logs
      - ./backend/bots/ml-learning-engine/models:/app/models
      - ./backend/bots/ml-learning-engine/notebooks:/app/notebooks

  # Notification Bot
  notification-bot:
    build:
      context: ./backend/bots/notification-bot
      dockerfile: Dockerfile
    container_name: crypto-notification-bot
    restart: unless-stopped
    env_file:
      - secrets/database.txt
      - secrets/notification.txt
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/notification-bot/logs:/app/logs

  # Feedback Processor Bot
  feedback-processor-bot:
    build:
      context: ./backend/bots/feedback-processor-bot
      dockerfile: Dockerfile
    container_name: crypto-feedback-processor
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-network
    volumes:
      - ./backend/bots/feedback-processor-bot/logs:/app/logs

  # ==================== FRONTEND ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
        VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:3000}
    container_name: crypto-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - api-gateway
    networks:
      - crypto-network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  # ==================== MONITORING ====================
  prometheus:
    image: prom/prometheus:latest
    container_name: crypto-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - crypto-network

  grafana:
    image: grafana/grafana:latest
    container_name: crypto-grafana
    restart: unless-stopped
    env_file:
      - secrets/database.txt
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - crypto-network

  # ==================== REVERSE PROXY ====================
  nginx:
    image: nginx:alpine
    container_name: crypto-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/sites-available:/etc/nginx/sites-available
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
      - frontend
    networks:
      - crypto-network
