name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        # Install bot-specific dependencies
        if [ -f backend/bots/market-data-bot/requirements.txt ]; then
          pip install -r backend/bots/market-data-bot/requirements.txt
        fi
        # Optionally install root requirements if needed for shared deps
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # Target only the bot's source code
        BOT_PATH="backend/bots/market-data-bot/src"
        # Stop on syntax errors or undefined names
        flake8 $BOT_PATH --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings, with custom limits
        flake8 $BOT_PATH --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        # Run tests specifically for the bot directory
        pytest backend/bots/market-data-bot -v --tb=short
        # Optional: Add coverage if pytest-cov is in requirements.txt
        # pytest backend/bots/market-data-bot --cov=src --cov-report=xml